package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1

/**
 * Associados generated by hbm2java
 */
public class Associados implements java.io.Serializable {

    private long idAssociado;
    private String nomeAssociado;
    private String cpfAssociado;
    private String rgAssociado;
    private String dataNascimento;
    private String cep;
    private String uf;
    private String cidadeAssociado;
    private String endBairro;
    private String endRua;
    private Short endNum;
    private String telefone;

    public Associados() {
    }

    public Associados(long idAssociado, String nomeAssociado, String cpfAssociado, String rgAssociado, String dataNascimento, String cep, String uf, String cidadeAssociado, String endBairro, String endRua, Short endNum, String telefone) {
        this.idAssociado = idAssociado;
        this.nomeAssociado = nomeAssociado;
        this.cpfAssociado = cpfAssociado;
        this.rgAssociado = rgAssociado;
        this.dataNascimento = dataNascimento;
        this.cep = cep;
        this.uf = uf;
        this.cidadeAssociado = cidadeAssociado;
        this.endBairro = endBairro;
        this.endRua = endRua;
        this.endNum = endNum;
        this.telefone = telefone;
    }

    public Associados(String nomeAssociado, String cpfAssociado, String rgAssociado, String dataNascimento, String cep, String uf, String cidadeAssociado, String endBairro, String endRua, Short endNum, String telefone) {
        this.nomeAssociado = nomeAssociado;
        this.cpfAssociado = cpfAssociado;
        this.rgAssociado = rgAssociado;
        this.dataNascimento = dataNascimento;
        this.cep = cep;
        this.uf = uf;
        this.cidadeAssociado = cidadeAssociado;
        this.endBairro = endBairro;
        this.endRua = endRua;
        this.endNum = endNum;
        this.telefone = telefone;
    }
    
    public String getNomeAssociado() {
        return nomeAssociado;
    }

    public void setNomeAssociado(String nomeAssociado) {
        this.nomeAssociado = nomeAssociado;
    }

    public long getIdAssociado() {
        return this.idAssociado;
    }

    public void setIdAssociado(long idAssociado) {
        this.idAssociado = idAssociado;
    }

    public String getCpfAssociado() {
        return this.cpfAssociado;
    }

    public void setCpfAssociado(String cpfAssociado) {
        this.cpfAssociado = cpfAssociado;
    }

    public String getRgAssociado() {
        return this.rgAssociado;
    }

    public void setRgAssociado(String rgAssociado) {
        this.rgAssociado = rgAssociado;
    }

    public String getDataNascimento() {
        return dataNascimento;
    }

    public void setDataNascimento(String dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    
    public Short getEndNum() {
        return this.endNum;
    }

    public void setEndNum(Short endNum) {
        this.endNum = endNum;
    }

    public String getEndRua() {
        return this.endRua;
    }

    public void setEndRua(String endRua) {
        this.endRua = endRua;
    }

    public String getEndBairro() {
        return this.endBairro;
    }

    public void setEndBairro(String endBairro) {
        this.endBairro = endBairro;
    }

    public String getUf() {
        return this.uf;
    }

    public void setUf(String uf) {
        this.uf = uf;
    }

    public String getCidadeAssociado() {
        return cidadeAssociado;
    }

    public void setCidadeAssociado(String cidadeAssociado) {
        this.cidadeAssociado = cidadeAssociado;
    }

    public String getTelefone() {
        return telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public String getCep() {
        return cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

}
