package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Compras generated by hbm2java
 */
public class Compras implements java.io.Serializable {

    private long idCompra;
    private long idAssociado;
    private String data;

    public Compras() {
    }

    public Compras(long idAssociado, String data) {
        this.idAssociado = idAssociado;
        this.data = data;
    }

    public Compras(long idAssociado) {
        this.idAssociado = idAssociado;
    }
    
    public Compras(long idCompra, long idAssociado, String data) {
        this.idCompra = idCompra;
        this.idAssociado = idAssociado;
        this.data = data;
    }

    public long getIdCompra() {
        return idCompra;
    }

    public void setIdCompra(long idCompra) {
        this.idCompra = idCompra;
    }

    public long getIdAssociado() {
        return idAssociado;
    }

    public void setIdAssociado(long idAssociado) {
        this.idAssociado = idAssociado;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }
    
}
