package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1



/**
 * Despesas generated by hbm2java
 */
public class Despesas  implements java.io.Serializable {


     private long id_despesa;
     private String titulo;
     private double valor;
     private String tipo;
     private String data;

    public Despesas() {
    }

    public Despesas(String titulo, double valor, String tipo, String data) {
        this.titulo = titulo;
        this.valor = valor;
        this.tipo = tipo;
        this.data = data;
    }

    public Despesas(long id_despesa, String titulo, double valor, String tipo, String data) {
        this.id_despesa = id_despesa;
        this.titulo = titulo;
        this.valor = valor;
        this.tipo = tipo;
        this.data = data;
    }

    public long getId_despesa() {
        return id_despesa;
    }

    public void setId_despesa(long id_despesa) {
        this.id_despesa = id_despesa;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public double getValor() {
        return valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }
}


