package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1



/**
 * Despesas generated by hbm2java
 */
public class Despesas  implements java.io.Serializable {


     private long idDespesa;
     private String titulo;
     private Integer valor;

    public Despesas() {
    }

	
    public Despesas(int idDespesa) {
        this.idDespesa = idDespesa;
    }
   
    public long getIdDespesa() {
        return this.idDespesa;
    }
    
    public void setIdDespesa(long idDespesa) {
        this.idDespesa = idDespesa;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }




}


