package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1

import java.util.ArrayList;

/**
 * ItensVendidos generated by hbm2java
 */
public class ItemVendido implements java.io.Serializable {

    private long id_material;
    private long id_venda;
    private double quantidade;
    private double preco_kg;
    private double preco_total;

    public ItemVendido(long id_material, long id_venda, double quantidade, double preco_kg, double preco_total) {
        this.id_material = id_material;
        this.id_venda = id_venda;
        this.quantidade = quantidade;
        this.preco_kg = preco_kg;
        this.preco_total = preco_total;
    }

    public ItemVendido() {
    }

    public ItemVendido(long id_material, double quantidade, double preco_kg, double preco_total) {
        this.id_material = id_material;
        this.quantidade = quantidade;
        this.preco_kg = preco_kg;
        this.preco_total = preco_total;
    }

    public long getId_material() {
        return id_material;
    }

    public void setId_material(long id_material) {
        this.id_material = id_material;
    }

    public long getId_venda() {
        return id_venda;
    }

    public void setId_venda(long id_venda) {
        this.id_venda = id_venda;
    }

    public double getQuantidade() {
        return quantidade;
    }

    public void setQuantidade(double quantidade) {
        this.quantidade = quantidade;
    }

    public double getPreco_kg() {
        return preco_kg;
    }

    public void setPreco_kg(double preco_kg) {
        this.preco_kg = preco_kg;
    }

    public double getPreco_total() {
        return preco_total;
    }

    public void setPreco_total(double preco_total) {
        this.preco_total = preco_total;
    }

}
