package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1

import java.util.Set;

/**
 * Materiais generated by hbm2java
 */
public class Materiais implements java.io.Serializable {

    private long idMaterial;
    private String materialNome;
    private String tipoMaterial;

    public Materiais() {
    }

    public Materiais(long idMaterial) {
        this.idMaterial = idMaterial;
    }

    public Materiais(long idMaterial, String materialNome, String tipoMaterial) {
        this.idMaterial = idMaterial;
        this.materialNome = materialNome;
        this.tipoMaterial = tipoMaterial;
    }

    public Materiais(String nome, String tipo) {
        this.materialNome = nome;
        this.tipoMaterial = tipo;
    }

    public long getIdMaterial() {
        return this.idMaterial;
    }

    public void setIdMaterial(long idMaterial) {
        this.idMaterial = idMaterial;
    }

    public String getMaterialNome() {
        return this.materialNome;
    }

    public void setMaterialNome(String materialNome) {
        this.materialNome = materialNome;
    }

    public String getTipoMaterial() {
        return this.tipoMaterial;
    }

    public void setTipoMaterial(String tipoMaterial) {
        this.tipoMaterial = tipoMaterial;
    }

}
