package model;
// Generated 08/08/2018 15:24:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendas generated by hbm2java
 */
public class Vendas  implements java.io.Serializable {


     private long id_venda;
     private long id_empresa;

     String data;
     private Boolean nota_fiscal;

    public Vendas(long id_venda, long id_empresa, String data, Boolean nota_fiscal) {
        this.id_venda = id_venda;
        this.id_empresa = id_empresa;
        this.data = data;
        this.nota_fiscal = nota_fiscal;
    }

    public Vendas(long id_empresa, Boolean nota_fiscal) {
        this.id_empresa = id_empresa;
        this.nota_fiscal = nota_fiscal;
    }
    
    public Vendas(String data, Boolean nota_fiscal) {
        this.data = data;
        this.nota_fiscal = nota_fiscal;
    }

    public long getId_venda() {
        return id_venda;
    }

    public void setId_venda(long id_venda) {
        this.id_venda = id_venda;
    }

    public long getId_empresa() {
        return id_empresa;
    }

    public void setId_empresa(long id_empresa) {
        this.id_empresa = id_empresa;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Boolean getNota_fiscal() {
        return nota_fiscal;
    }

    public void setNota_fiscal(Boolean nota_fiscal) {
        this.nota_fiscal = nota_fiscal;
    }
     
}


