/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.principalController;
import javax.swing.JOptionPane;
import model.Despesas;
import model.Despesas;

/**
 *
 * @author Bento
 */
public class fichaDespesaForm extends javax.swing.JFrame {

    principalController controllerPrincipal;
    Despesas despesa;
    principalView pv;

    boolean hasErrors = false;
    String error = "";

    /**
     * Creates new form cadastrarDespesaForm
     */
    public fichaDespesaForm(principalController pc, Despesas despesa, principalView pv) {
        this.controllerPrincipal = pc;
        this.despesa = despesa;
        this.pv = pv;
        initComponents();
        if (despesa != null) {
            tituloTextField.setText(despesa.getTitulo());
            valorTextField.setText(String.valueOf(despesa.getValor()));
            tipoComboBox.setSelectedIndex(findSelectedIndex(despesa.getTipo()));
            dataTextField.setText(despesa.getData());
        }
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    //Busca o index de um tal elemento da comboBox
    private int findSelectedIndex(String s) {
        for (int i = 0; i < tipoComboBox.getItemCount(); i++) {
            if (tipoComboBox.getItemAt(i).toString().equals(s)) {
                return i;
            }
        }
        return -1;//É nula a chance de retorno -1
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tituloTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        valorTextField = new javax.swing.JTextField();
        confirmarDespesaButton = new javax.swing.JButton();
        cancelarDespesaButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        tipoComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dataTextField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ficha de Cadastro de Despesa");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Titulo*:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo*:");

        valorTextField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        valorTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        confirmarDespesaButton.setBackground(new java.awt.Color(1, 103, 204));
        confirmarDespesaButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        confirmarDespesaButton.setForeground(new java.awt.Color(51, 51, 51));
        confirmarDespesaButton.setText("Confirmar");
        confirmarDespesaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarDespesaButtonActionPerformed(evt);
            }
        });

        cancelarDespesaButton.setBackground(new java.awt.Color(156, 36, 33));
        cancelarDespesaButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cancelarDespesaButton.setForeground(new java.awt.Color(51, 51, 51));
        cancelarDespesaButton.setText("Cancelar");
        cancelarDespesaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarDespesaButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Os campos marcados com * são obrigatórios! ");

        tipoComboBox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alimentação", "Veículo", "Associados", "Barração", "Outros" }));
        tipoComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Valor*:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Data*:");

        try {
            dataTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dataTextField.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tituloTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataTextField)))
                .addContainerGap())
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmarDespesaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarDespesaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataTextField)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(valorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(confirmarDespesaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelarDespesaButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarDespesaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarDespesaButtonActionPerformed
        //Garante que todos os campos necessarios foram preenchidos e validados
        if (tituloTextField.getText().equals("")
                && valorTextField.getText().equals("")
                && dataTextField.getText().equals("")) {
            hasErrors = true;
            error += "->Preencha todos campos obrigatórios para concluir o cadastro!\n";
        } else {
            if (tituloTextField.getText().length() > 100) {
                hasErrors = true;
                error += "->O Titulo digitado é muito grande!\n";
            }

            if (Float.parseFloat(valorTextField.getText()) < 0) {
                hasErrors = true;
                error += "->Valor invalido!\n";
            }
            
            if (dataTextField.getText().replace(" ", "").replace("/", "").length() < 8) {
                hasErrors = true;
                error += "->Data invalido!\n";
            }
        }

        //Se nao possuir erros o programa procede com o planejado
        if (!hasErrors) {
            if (despesa == null) {
                //Cadastra um novo associado
                controllerPrincipal.getControladorDespesas().adicionarDespesa(tituloTextField.getText(),
                        tipoComboBox.getItemAt(tipoComboBox.getSelectedIndex()),Double.parseDouble(valorTextField.getText()),dataTextField.getText());
                //Confirma cadastro
                JOptionPane.showMessageDialog(null, "Cadastro Concluido com Sucesso!");
                //Pergunta se quer cadastrar mais um
                if (JOptionPane.showConfirmDialog(null, "Deseja cadastrar outra Despesa?") == JOptionPane.YES_OPTION) {
                    tituloTextField.setText("");
                    valorTextField.setText("");
                } else {
                    this.dispose();//Fecha a tela caso não queira fazer mais nenhum cadastro
                }
            } else {
                //Edita um associado, enviando o antigo registro do mesmo e o novo registro para troca
                controllerPrincipal.getControladorDespesas().editarDespesa(despesa, new Despesas(tituloTextField.getText(),
                        Double.parseDouble(valorTextField.getText()),tipoComboBox.getItemAt(tipoComboBox.getSelectedIndex()),
                        dataTextField.getText()));
                //Confirma cadastro
                JOptionPane.showMessageDialog(null, "Edição Concluida com Sucesso!");
                this.dispose();//Fecha a tela caso não queira fazer mais nenhum cadastro
            }

            //Atualiza tabela na view principal
            pv.preencherTabela("Despesas", pv.getjTableDespesas());
        } else {
            //Mostra erros
            JOptionPane.showMessageDialog(null, error);
        }
    }//GEN-LAST:event_confirmarDespesaButtonActionPerformed

    private void cancelarDespesaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarDespesaButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarDespesaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarDespesaButton;
    private javax.swing.JButton confirmarDespesaButton;
    private javax.swing.JFormattedTextField dataTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> tipoComboBox;
    private javax.swing.JTextField tituloTextField;
    private javax.swing.JTextField valorTextField;
    // End of variables declaration//GEN-END:variables
}
