/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import acari.modeloTabelaItensComprados;
import controller.principalController;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Associados;
import model.ItemComprado;

/**
 *
 * @author Bento
 */
public class listaItensCompradosForm extends javax.swing.JFrame {

    principalController principalControlador;
    long id_compra_master;
    principalView pv;
    boolean hasErrors = false;
    String error = "";

    /**
     * Creates new form cadastrarAssociadoForm
     */
    public listaItensCompradosForm(principalController principalControlador, long id_compra_master, principalView pv) {
        this.principalControlador = principalControlador;
        this.id_compra_master = id_compra_master;
        this.pv = pv;
        initComponents();

        preencherTabela();

        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTableItensComprados = new javax.swing.JTable();
        editarItemCompradoListaButton = new javax.swing.JButton();
        cadastrarItemCompradoListaButton = new javax.swing.JButton();
        excluirItemCompradoListaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        principalPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Lista de Itens Comprados");

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Pesquisa por Nome:");

        jTableItensComprados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "RG", "Rua", "Número", "Complemento", "Bairro", "Cidade", "UF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(jTableItensComprados);

        editarItemCompradoListaButton.setBackground(new java.awt.Color(204, 204, 0));
        editarItemCompradoListaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        editarItemCompradoListaButton.setForeground(new java.awt.Color(51, 51, 0));
        editarItemCompradoListaButton.setText("Editar Item");
        editarItemCompradoListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarItemCompradoListaButtonActionPerformed(evt);
            }
        });

        cadastrarItemCompradoListaButton.setBackground(new java.awt.Color(51, 153, 0));
        cadastrarItemCompradoListaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cadastrarItemCompradoListaButton.setForeground(new java.awt.Color(33, 57, 8));
        cadastrarItemCompradoListaButton.setText("Cadastrar Novo Item");
        cadastrarItemCompradoListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarItemCompradoListaButtonActionPerformed(evt);
            }
        });

        excluirItemCompradoListaButton.setBackground(new java.awt.Color(156, 36, 33));
        excluirItemCompradoListaButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        excluirItemCompradoListaButton.setForeground(new java.awt.Color(56, 22, 20));
        excluirItemCompradoListaButton.setText("Excluir Item");
        excluirItemCompradoListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirItemCompradoListaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout principalPanelLayout = new javax.swing.GroupLayout(principalPanel);
        principalPanel.setLayout(principalPanelLayout);
        principalPanelLayout.setHorizontalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(editarItemCompradoListaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGap(740, 740, 740)
                .addComponent(excluirItemCompradoListaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(cadastrarItemCompradoListaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        principalPanelLayout.setVerticalGroup(
            principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(principalPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(principalPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editarItemCompradoListaButton)
                            .addComponent(excluirItemCompradoListaButton)
                            .addComponent(cadastrarItemCompradoListaButton))))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(principalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(principalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(principalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarItemCompradoListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarItemCompradoListaButtonActionPerformed
        //Pega a tabela e transforma num modelo o qual podemos manipular seu conteudo
        modeloTabelaItensComprados model = (modeloTabelaItensComprados) jTableItensComprados.getModel();
        //Validamos o resultado
        if (jTableItensComprados.getSelectedRow() != -1) {
            //Pegamos os dados selecionados na tabela e encontramos o modelo na lista de associados
            ItemComprado item = principalControlador.getControladorCompras().getEspecificItem(
                    id_compra_master, model.getLinhas().get(jTableItensComprados.getSelectedRow()).getId_material()
            );
            if (item != null) {
                new fichaItemCompradoForm(principalControlador, item, id_compra_master, this);//iniciamos a tela enviando um modelo
            }
        } else {
            JOptionPane.showMessageDialog(null, "Favor selecionar um associado na tabela primeiro!");
        }
    }//GEN-LAST:event_editarItemCompradoListaButtonActionPerformed

    private void cadastrarItemCompradoListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarItemCompradoListaButtonActionPerformed
        new fichaItemCompradoForm(principalControlador, null, id_compra_master, this);
    }//GEN-LAST:event_cadastrarItemCompradoListaButtonActionPerformed

    private void excluirItemCompradoListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirItemCompradoListaButtonActionPerformed
        //Pega a tabela e transforma num modelo o qual podemos manipular seu conteudo
        modeloTabelaItensComprados model = (modeloTabelaItensComprados) jTableItensComprados.getModel();
        //Validamos o resultado
        if (jTableItensComprados.getSelectedRow() != -1) {
            //Pegamos os dados selecionados na tabela e encontramos o modelo na lista de associados
            
            principalControlador.getControladorCompras().removeItem(
                    id_compra_master,
                    model.getLinhas().get(jTableItensComprados.getSelectedRow()).getId_material()
            );
        } else {
            JOptionPane.showMessageDialog(null, "Favor selecionar uma empresa na tabela primeiro!");
        }
        preencherTabela();
    }//GEN-LAST:event_excluirItemCompradoListaButtonActionPerformed

    public void preencherTabela() {
        JTable table = jTableItensComprados;
        modeloTabelaItensComprados modeloIC = null;

        modeloIC = new modeloTabelaItensComprados(principalControlador.getControladorCompras().getItensFromCompraID(id_compra_master), principalControlador);
        if (modeloIC != null) {
            table.setModel(modeloIC);
            table.getTableHeader().setReorderingAllowed(false);
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao procurar a tabela para preenchimento!!!", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarItemCompradoListaButton;
    private javax.swing.JButton editarItemCompradoListaButton;
    private javax.swing.JButton excluirItemCompradoListaButton;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTableItensComprados;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel principalPanel;
    // End of variables declaration//GEN-END:variables

}
