/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Bento
 */
public class principalView extends javax.swing.JFrame {

    /**
     * Creates new form principalView
     */
    public principalView() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("logoProject.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img.getScaledInstance(logoLabel.getWidth(), logoLabel.getHeight(),
        Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        logoLabel.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoPanel = new javax.swing.JPanel();
        pagIniPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comprarPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        venderPanel = new javax.swing.JPanel();
        relatoriosPanel = new javax.swing.JPanel();
        associadosPanel = new javax.swing.JPanel();
        empresasPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        menuButtonsPanel = new javax.swing.JPanel();
        pagIniButton = new javax.swing.JButton();
        comprarButton = new javax.swing.JButton();
        venderButton = new javax.swing.JButton();
        relatoriosButton = new javax.swing.JButton();
        associadosButton = new javax.swing.JButton();
        empresasButton = new javax.swing.JButton();
        sairButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        setPreferredSize(new java.awt.Dimension(1300, 600));

        infoPanel.setBackground(new java.awt.Color(204, 255, 204));
        infoPanel.setLayout(new java.awt.CardLayout());

        pagIniPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/acariApresentacao.png"))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("® Desenvolvido por Ruan M. Adabo & Ian M. Tobar");

        javax.swing.GroupLayout pagIniPanelLayout = new javax.swing.GroupLayout(pagIniPanel);
        pagIniPanel.setLayout(pagIniPanelLayout);
        pagIniPanelLayout.setHorizontalGroup(
            pagIniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pagIniPanelLayout.setVerticalGroup(
            pagIniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pagIniPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        infoPanel.add(pagIniPanel, "card2");

        comprarPanel.setBackground(new java.awt.Color(204, 204, 204));
        comprarPanel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Informações do Item");
        comprarPanel.add(jLabel3);
        jLabel3.setBounds(0, 0, 790, 40);

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("AOSKDADMADPSASDPLASD\nAPSDKMADSM\nlaksdmmnkad\nlkansdkadmçlasmas\n\napçskdmpçkasdmpçasdmkçasd\nasd\nad\nsaçdmklsçkadmsaçkdms\nad\nadslakmnsdklmadskads\nads\nadskasmndsklmads");
        jScrollPane1.setViewportView(jTextArea1);

        comprarPanel.add(jScrollPane1);
        jScrollPane1.setBounds(800, 50, 320, 390);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Informações da Compra");
        comprarPanel.add(jLabel4);
        jLabel4.setBounds(791, 0, 350, 40);

        jButton1.setBackground(new java.awt.Color(156, 36, 33));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Cancelar");
        comprarPanel.add(jButton1);
        jButton1.setBounds(800, 520, 320, 30);

        jButton2.setBackground(new java.awt.Color(1, 103, 204));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Confirmar");
        comprarPanel.add(jButton2);
        jButton2.setBounds(800, 480, 320, 30);
        comprarPanel.add(jSeparator1);
        jSeparator1.setBounds(0, 40, 1140, 20);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total a Pagar: R$0000,00");
        comprarPanel.add(jLabel5);
        jLabel5.setBounds(800, 440, 320, 40);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Associado:");
        comprarPanel.add(jLabel6);
        jLabel6.setBounds(70, 70, 340, 30);

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Raul Seixas dos Santos da Silva", "Flora Guenzburguer Baumann Somogyi", "Item 3", "Item 4" }));
        comprarPanel.add(jComboBox1);
        jComboBox1.setBounds(70, 100, 340, 30);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        comprarPanel.add(jSeparator2);
        jSeparator2.setBounds(790, 0, 70, 610);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Preço Por Kilo (em Reais):");
        comprarPanel.add(jLabel7);
        jLabel7.setBounds(70, 310, 300, 30);

        jComboBox2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motor de Geladeira", "Item 2", "Item 3", "Item 4" }));
        comprarPanel.add(jComboBox2);
        jComboBox2.setBounds(490, 100, 230, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Material:");
        comprarPanel.add(jLabel8);
        jLabel8.setBounds(490, 70, 230, 30);

        jTextField1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("00,00");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        comprarPanel.add(jTextField1);
        jTextField1.setBounds(380, 310, 80, 30);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Quantidade (em Kilos):");
        comprarPanel.add(jLabel9);
        jLabel9.setBounds(70, 250, 270, 30);

        jTextField2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("00000");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        comprarPanel.add(jTextField2);
        jTextField2.setBounds(340, 250, 80, 30);

        jButton3.setBackground(new java.awt.Color(51, 153, 0));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(33, 57, 8));
        jButton3.setText("Cadastrar Novo Material");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        comprarPanel.add(jButton3);
        jButton3.setBounds(480, 140, 250, 40);

        jButton4.setBackground(new java.awt.Color(51, 153, 0));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(33, 57, 8));
        jButton4.setText("Adicionar Item");
        comprarPanel.add(jButton4);
        jButton4.setBounds(70, 470, 320, 70);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Preço Total (em Reais):");
        comprarPanel.add(jLabel10);
        jLabel10.setBounds(70, 370, 270, 30);

        jTextField3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0000,00");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        comprarPanel.add(jTextField3);
        jTextField3.setBounds(350, 370, 110, 30);

        jButton5.setBackground(new java.awt.Color(51, 153, 0));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(33, 57, 8));
        jButton5.setText("Cadastrar Novo Associado");
        comprarPanel.add(jButton5);
        jButton5.setBounds(70, 140, 340, 40);

        infoPanel.add(comprarPanel, "card2");

        javax.swing.GroupLayout venderPanelLayout = new javax.swing.GroupLayout(venderPanel);
        venderPanel.setLayout(venderPanelLayout);
        venderPanelLayout.setHorizontalGroup(
            venderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        venderPanelLayout.setVerticalGroup(
            venderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        infoPanel.add(venderPanel, "card2");

        javax.swing.GroupLayout relatoriosPanelLayout = new javax.swing.GroupLayout(relatoriosPanel);
        relatoriosPanel.setLayout(relatoriosPanelLayout);
        relatoriosPanelLayout.setHorizontalGroup(
            relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        relatoriosPanelLayout.setVerticalGroup(
            relatoriosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        infoPanel.add(relatoriosPanel, "card2");

        javax.swing.GroupLayout associadosPanelLayout = new javax.swing.GroupLayout(associadosPanel);
        associadosPanel.setLayout(associadosPanelLayout);
        associadosPanelLayout.setHorizontalGroup(
            associadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        associadosPanelLayout.setVerticalGroup(
            associadosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        infoPanel.add(associadosPanel, "card2");

        javax.swing.GroupLayout empresasPanelLayout = new javax.swing.GroupLayout(empresasPanel);
        empresasPanel.setLayout(empresasPanelLayout);
        empresasPanelLayout.setHorizontalGroup(
            empresasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        empresasPanelLayout.setVerticalGroup(
            empresasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        infoPanel.add(empresasPanel, "card2");

        menuPanel.setBackground(new java.awt.Color(50, 165, 54));

        menuButtonsPanel.setBackground(new java.awt.Color(50, 165, 54));
        menuButtonsPanel.setLayout(new java.awt.GridLayout(7, 1));

        pagIniButton.setBackground(new java.awt.Color(50, 144, 55));
        pagIniButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pagIniButton.setForeground(new java.awt.Color(0, 0, 0));
        pagIniButton.setText("Pagina Inicial");
        pagIniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagIniButtonActionPerformed(evt);
            }
        });
        menuButtonsPanel.add(pagIniButton);

        comprarButton.setBackground(new java.awt.Color(50, 144, 55));
        comprarButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        comprarButton.setForeground(new java.awt.Color(0, 0, 0));
        comprarButton.setText("Comprar");
        comprarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarButtonActionPerformed(evt);
            }
        });
        menuButtonsPanel.add(comprarButton);

        venderButton.setBackground(new java.awt.Color(50, 144, 55));
        venderButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        venderButton.setForeground(new java.awt.Color(0, 0, 0));
        venderButton.setText("Vender");
        menuButtonsPanel.add(venderButton);

        relatoriosButton.setBackground(new java.awt.Color(50, 144, 55));
        relatoriosButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        relatoriosButton.setForeground(new java.awt.Color(0, 0, 0));
        relatoriosButton.setText("Relatórios");
        menuButtonsPanel.add(relatoriosButton);

        associadosButton.setBackground(new java.awt.Color(50, 144, 55));
        associadosButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        associadosButton.setForeground(new java.awt.Color(0, 0, 0));
        associadosButton.setText("Associados");
        menuButtonsPanel.add(associadosButton);

        empresasButton.setBackground(new java.awt.Color(50, 144, 55));
        empresasButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        empresasButton.setForeground(new java.awt.Color(0, 0, 0));
        empresasButton.setText("Empresas");
        menuButtonsPanel.add(empresasButton);

        sairButton.setBackground(new java.awt.Color(50, 144, 55));
        sairButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sairButton.setForeground(new java.awt.Color(0, 0, 0));
        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        menuButtonsPanel.add(sairButton);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarButtonActionPerformed
        infoPanel.removeAll();
        infoPanel.add(comprarPanel);
        infoPanel.repaint();
        infoPanel.revalidate();
    }//GEN-LAST:event_comprarButtonActionPerformed

    private void pagIniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagIniButtonActionPerformed
        infoPanel.removeAll();
        infoPanel.add(pagIniPanel);
        infoPanel.repaint();
        infoPanel.revalidate();
    }//GEN-LAST:event_pagIniButtonActionPerformed

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_sairButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton associadosButton;
    private javax.swing.JPanel associadosPanel;
    private javax.swing.JButton comprarButton;
    private javax.swing.JPanel comprarPanel;
    private javax.swing.JButton empresasButton;
    private javax.swing.JPanel empresasPanel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel menuButtonsPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton pagIniButton;
    private javax.swing.JPanel pagIniPanel;
    private javax.swing.JButton relatoriosButton;
    private javax.swing.JPanel relatoriosPanel;
    private javax.swing.JButton sairButton;
    private javax.swing.JButton venderButton;
    private javax.swing.JPanel venderPanel;
    // End of variables declaration//GEN-END:variables
}
